name: Certora

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: Certora/certora-run-action@v1
        with:
          configurations: |-
            certora/confs/AccrueInterest.conf
            certora/confs/AssetsAccounting.conf
            certora/confs/ConsistentState.conf
            certora/confs/ExactMath.conf
            certora/confs/ExchangeRate.conf
            certora/confs/Health.conf
            certora/confs/LibSummary.conf
            certora/confs/LiquidateBuffer.conf
            certora/confs/Liveness.conf
            certora/confs/Reentrancy.conf
            certora/confs/Reverts.conf
            certora/confs/StayHealthy.conf
            certora/confs/Transfer.conf
          solc-versions: 0.8.19
          job-name: "Certora Run"
          certora-key: ${{ secrets.CERTORAKEY }}
          compilation-steps-only: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
